name: Python Automation with Chrome Headless

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure you have a requirements.txt file with your dependencies

    - name: Run tests
      run: |
        python -m pytest --headless --alluredir=allure-results

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: allure-results  # Replace with the actual path to your allure-results directory
